import StyleDictionary from 'style-dictionary';
import {formats, transformGroups} from 'style-dictionary/enums';

/**
 * A list of the themes that will be generated by this file.
 */
const themes = ['kid'];

/**
 * Custom filter that excludes all tokens that are found in the `base` directory.
 */
StyleDictionary.registerFilter({
  name: 'is-semantic',
  filter: (token) => {
    // This will only include tokens that are NOT in the 'base' folder
    return token.filePath.indexOf('base') === -1;
  },
});

/**
 * Configuration shared across all themes
 */
const config = {
  log: {
    verbosity: 'verbose',
  },
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      buildPath: 'src/assets/css/automated/',
    },
  },
  source: ['tokens/base/**/*.json'],
};

/**
 * Create style dictionary that will be extended by the global and theme style dictionaries.
 */
const baseStyleDictionary = new StyleDictionary(config);

/**
 * Create the global style dictionary
 */
const globalStyleDictionary = await baseStyleDictionary.extend(
  Object.assign(structuredClone(config), {
    platforms: {
      css: {
        files: [
          {
            destination: `variables.css`,
            filter: 'is-semantic',
            format: formats.cssVariables,
          },
        ],
      },
    },
    source: ['tokens/global/**/*.json'],
  }),
);
await globalStyleDictionary.buildAllPlatforms();

/**
 * Define tokens based on kid’s favorite color.
 */
const themeConfig = Object.assign(structuredClone(config), {
  platforms: {
    css: {
      files: [
        {
          destination: `variables-kid.css`,
          filter: 'is-semantic',
          format: formats.cssVariables,
          options: {
            // Keeps CSS Custom Properties instead of replacing them with values.
            outputReferences: true,
            outputReferenceFallbacks: true,
            // This option wraps the CSS variables in the specified selector
            selector: `.kid`,
          },
        },
      ],
    },
  },
  source: [`tokens/theme/tokens-kid.json`],
});

const themeStyleDictionary = await baseStyleDictionary.extend(themeConfig);
await themeStyleDictionary.buildAllPlatforms();